FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache openssl

COPY package.json ./
COPY tsconfig.base.json ./
COPY prisma ./prisma
COPY packages ./packages
COPY services ./services

RUN npm install
RUN npx prisma generate --schema=prisma/schema.prisma

ARG SERVICE_NAME

WORKDIR /app/services/${SERVICE_NAME}

CMD ["npm", "run", "dev"]
